import { useEffect, useRef, useState } from "preact/hooks";
import type { RPCListener, Session } from "./app";
import { action, read } from "./api";

type Job = { id:string; rpcListenerId:string; fromBlock:number; toBlock:number; state:string; processedBlocks:number; createdEvents:number; createdDeliveries:number; duplicates:number; failureSummary?:string; configurationRevision:number };
type Preview = { chainId:number; fromBlock:number; toBlock:number; blocks:number; configurationRevision:number; destinations:string[] };
const terminal=(state:string)=>state==="completed"||state==="cancelled";

export function BackfillsPage({session,listeners}:{session:Session;listeners:RPCListener[]}) {
 const [jobs,setJobs]=useState<Job[]>([]),[listener,setListener]=useState(listeners[0]?.id??""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[preview,setPreview]=useState<Preview>(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const fromInput=useRef<HTMLInputElement>(null),toInput=useRef<HTMLInputElement>(null); const names=new Map(listeners.map(item=>[item.id,item.name])); const selectedListener=listener||listeners[0]?.id||""; const body=()=>({rpcListenerId:selectedListener,fromBlock:Number(fromInput.current?.value??from),toBlock:Number(toInput.current?.value??to),mode:"backfill-missing"});
 async function load(){try{setJobs((await read<{entries:Job[]|null}>("/api/v1/backfills?limit=100")).entries??[])}catch(e){setError(e instanceof Error?e.message:"Backfill jobs are unavailable.")}}
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{if(listeners.length>0&&!listeners.some(item=>item.id===listener)){setListener(listeners[0].id);setPreview(undefined)}},[listeners,listener]);
 async function inspect(){setBusy(true);setError("");try{const result=await action<Preview>(session,"/api/v1/backfills/preview",body());setPreview({...result,destinations:result.destinations??[]})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function create(){if(!preview)return;setBusy(true);setError("");try{await action(session,"/api/v1/backfills",{...body(),confirm:true});setPreview(undefined);setFrom("");setTo("");await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function transition(id:string,name:string){const prompt=name==="cancel"?"Cancel this backfill? Already persisted events and deliveries will be kept.":"Resume this backfill and retry from its durable progress?";if(!window.confirm(prompt))return;setBusy(true);setError("");try{await action(session,`/api/v1/backfills/${id}/${name}`,{confirm:true});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(session.role!=="admin")return <section class="backfills-view"><div class="section-title"><div><p class="eyebrow">Historical operations</p><h1>Missing-event backfill</h1></div></div><article class="panel backfill-empty"><span>↶</span><h2>Administrator access required</h2><p>Backfill jobs change durable Engine state and are available to administrators only.</p></article></section>;
 return <section class="backfills-view">
  <div class="section-title backfill-heading"><div><p class="eyebrow">Historical operations</p><h1>Missing-event backfill</h1><p class="section-description">Recover missing blockchain events without resending or changing existing deliveries.</p></div><button class="button button--secondary" disabled={busy} onClick={()=>void load()}>{busy?"Working…":"Refresh jobs"}</button></div>
  {error&&<p class="alert" role="alert">{error}</p>}
  <div class="backfill-create-grid"><article class="panel backfill-create-card"><header><div><h2>Choose a block range</h2><p>Select one listener and an inclusive historical range.</p></div></header><form onSubmit={e=>{e.preventDefault();void inspect()}}><label>RPC listener<select value={selectedListener} required disabled={busy} onChange={e=>{setListener(e.currentTarget.value);setPreview(undefined)}}><option value="" disabled>Select a listener</option>{listeners.map(item=><option key={item.id} value={item.id}>{item.name} · chain {item.chainId}</option>)}</select></label><div class="backfill-range-fields"><label>From block<input ref={fromInput} type="number" min="0" required placeholder="Start block" value={from} disabled={busy} onInput={e=>{setFrom(e.currentTarget.value);setPreview(undefined)}}/></label><span>→</span><label>To block<input ref={toInput} type="number" min="0" required placeholder="End block" value={to} disabled={busy} onInput={e=>{setTo(e.currentTarget.value);setPreview(undefined)}}/></label></div><footer><span>Inclusive range</span><button class="button" type="submit" disabled={busy||!selectedListener}>{busy?"Checking…":"Preview backfill"}</button></footer></form></article>
  <aside class="panel backfill-safety-card"><span class="backfill-safety-icon">✓</span><h2>Missing events only</h2><p>This operation uses the route configuration captured when you create the job.</p><ul><li>Existing deliveries are never resent</li><li>New destinations are not attached to old events</li><li>Jobs can be paused, resumed, or cancelled</li></ul></aside></div>
  {preview&&<article class="panel backfill-preview"><header><div><h2>Review and confirm</h2><p>Configuration revision {preview.configurationRevision}</p></div></header><dl><div><dt>Network</dt><dd>Chain {preview.chainId}</dd></div><div><dt>Range</dt><dd>{preview.fromBlock.toLocaleString()}–{preview.toBlock.toLocaleString()}</dd></div><div><dt>Blocks</dt><dd>{preview.blocks.toLocaleString()}</dd></div><div><dt>Destinations</dt><dd>{preview.destinations.length}</dd></div></dl>{preview.destinations.length>0&&<details><summary>Show effective destinations</summary><ul>{preview.destinations.map(destination=><li><code>{destination}</code></li>)}</ul></details>}<footer><p>Starting creates a durable, resumable job.</p><div><button class="button button--secondary" disabled={busy} onClick={()=>setPreview(undefined)}>Edit range</button><button class="button" disabled={busy} onClick={()=>void create()}>Confirm and start</button></div></footer></article>}
  <div class="backfill-list-heading"><div><h2>Backfill jobs</h2><p>Durable progress refreshes automatically every five seconds.</p></div><span>{jobs.length} {jobs.length===1?"job":"jobs"}</span></div>
  <article class="panel backfill-jobs">{jobs.length===0?<div class="backfill-empty"><span>↶</span><h3>No backfill jobs yet</h3><p>Preview a historical block range above to create your first job.</p></div>:<div class="table-wrap"><table><thead><tr><th>Listener and range</th><th>Status</th><th>Progress</th><th>Results</th><th><span class="visually-hidden">Actions</span></th></tr></thead><tbody>{jobs.map(job=>{const total=job.toBlock-job.fromBlock+1,percent=Math.min(100,Math.round(job.processedBlocks/Math.max(1,total)*100));return <tr key={job.id}><td><strong>{names.get(job.rpcListenerId)??"Removed listener"}</strong><small>{job.fromBlock.toLocaleString()} → {job.toBlock.toLocaleString()} · rev {job.configurationRevision}</small></td><td><span class={`backfill-status backfill-status--${job.state}`}>{job.state}</span>{job.failureSummary&&<small class="backfill-failure">{job.failureSummary}</small>}</td><td><div class="backfill-progress"><span><i style={{width:`${percent}%`}}/></span><small>{job.processedBlocks.toLocaleString()} of {total.toLocaleString()} blocks · {percent}%</small></div></td><td><strong>{job.createdEvents.toLocaleString()} events</strong><small>{job.createdDeliveries.toLocaleString()} deliveries · {job.duplicates.toLocaleString()} existing</small></td><td><div class="backfill-actions">{(job.state==="running"||job.state==="queued")&&<button class="button button--secondary" disabled={busy} onClick={()=>void transition(job.id,"pause")}>Pause</button>}{(job.state==="paused"||job.state==="failed")&&<button class="button button--secondary" disabled={busy} onClick={()=>void transition(job.id,"resume")}>Resume</button>}{!terminal(job.state)&&<button class="button button--danger" disabled={busy} onClick={()=>void transition(job.id,"cancel")}>Cancel</button>}</div></td></tr>})}</tbody></table></div>}</article>
 </section>;
}
